### ISSUE TITLE
`lut-fauna-sexes` VS `lut-vertebrate-sexes`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#100]
These 2 APIs have similar values.
http://vocabs.paratoo.tern.org.au:1337/api/lut-fauna-sexes
http://vocabs.paratoo.tern.org.au:1337/api/lut-vertebrate-sexes
Which one is better? We are using the first one.

**Comment by j-robinson** [comment]
We have unified them into a singular LUT caleld lut-fauna-sexes
