### ISSUE TITLE
Basal area observable properties collections should have sub-collections

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/dawe-rlp-vocabs#104]
There should be sub-collections representing sub-protocols with `skos:member` values to the observable properties in that protocol.

Current, there is only one collection with all of the observable properties of the overall Basal Area module. 

Instead, what we want is the following:
```
- basal area
  - full dbh
    - ...
    - ...
  - lite dbh
    - ...
    - ...
  - basal wedge
    - ...
    - ...
```

**Comment by junrongYu** [comment]
Hi @edmondchuc , should we add sub collections for attributes as well?

**Comment by edmondchuc** [comment]
Maybe later we can but I think it's fine for now? Let's focus on the observable properties first.
