### ISSUE TITLE
`lithology type`, `coarse fragments lithology`, `outcrop lithology`, `surface strew lithology`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#123]
`lithology type` and `coarse fragments lithology` are from protocol `Soils`, and the former one is for rock outcrop.

`outcrop lithology` and `surface strew lithology` are from `Plot Description`.

They are using the same categorical API, should we take them as one property or keep them as module specific?

Originally from the discussion in https://github.com/ternaustralia/dawe-rlp-vocabs/pull/118#discussion_r910604545

**Comment by j-robinson** [comment]
These fields use the same values but refer to different elements in the landscape, so they should stay module specific.
