### ISSUE TITLE
slope and aspect are both an attribute and observable property

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/dawe-rlp-vocabs#126]
I believe it is not an attribute but I am not certain.

Below is the query to get concepts with more than one `schema:url` value.

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <https://schema.org/>
SELECT ?uri ?label (COUNT(?url) AS ?urlCount)
WHERE {
    ?uri a skos:Concept ;
         skos:prefLabel ?label ;
         
         # The url shows that it is a file in the attribute and observable property directory.
         # This is the problematic part. Why is it both an attribute and an observable property?
         # I don't think it is an attribute.
         schema:url ?url .
    
    # basal area sweep hit types has 2 urls because it is an observable property and it is defined in the custom_vocabs directory.
    filter(?uri != <https://linked.data.gov.au/def/test/dawe-cv/43178892-92a6-434f-9895-340700e299e6>)
}
GROUP BY ?uri ?label
HAVING (?urlCount > 1)
```

**Comment by junrongYu** [comment]
Hi @edmondchuc , they are identified as attributes in `Camera traps`, maybe we can delete the redundant attribute ones, and add them to `Camera traps` properties collection, is that okay?

**Comment by edmondchuc** [comment]
What is the feature type in camera traps for slow and aspect?

**Comment by junrongYu** [comment]
> What is the feature type in camera traps for slow and aspect?

No feature type currently because they were taken as attribute.

**Comment by edmondchuc** [comment]
I meant, what will be the feature type for slope and aspect in the camera traps module. We should also check why it was added as an attribute in the first place.

**Comment by edmondchuc** [comment]
In the camera traps module, section 4.1.2 Instructions and procedures, camera trap deployment (9), it says to record the slope and aspect as part of the camera trap's deployment. 

I think it was created as an attribute because when we model it with the information model, the slope and aspect becomes an attribute of the Deployment instance.

**Comment by arunherb** [comment]
I think the confusion with 'Slope' and 'aspect' is because of the way it is recorded in the camera-trap module and the way it has been documented in the information model. I think it should be a 'feature type' of the landform pattern, if we record this as a parameter of interest (i.e., observable property), especially in the 'camera trap module'. 

I would keep this as an observable property in this case and add 'landform pattern' as feature type.

**Comment by edmondchuc** [comment]
My concern is that the slope and aspect recorded here is only for deployment and redeployment purposes. It doesn't really make sense to record the deployment information as observations since it mentions in the protocol's redeployment section, _"the slope and aspect should match the deployment data"_.

**Comment by arunherb** [comment]
Hmmm.. I guess you are right in a way, because we do not derive any observable information, but it is just used for setting-up the camera and becomes a more quantifiable metric/descriptive summary of the habitat where the camera traps have been set-up. Probably matters more if re-deployed on a different slope or aspect from the first deployment. 

In any case do we keep it as an observable property then, because we already have it under this in the Plot Description module?

**Comment by edmondchuc** [comment]
I propose we keep it as both an attribute and observable property and delete the attribute file copy.

SSN and SOSA have the following classes `ssn:Property` and `sosa:ObservableProperty` to record information about entities. The latter records the value plus the additional metadata describing the observation. In the TERN Ontology, `tern:Attribute` is equivalent to `ssn:Property`. When it comes to deployment information, I don't see any value in recording the additional observation metadata, it is recorded only for redeployment purposes.

Also note that `sosa:ObservableProperty` is a subclass of `ssn:Property`.

**Comment by arunherb** [comment]
Cool. If the model can handle it well, we keep it under both categories. 
Thanks for clarifying. 
A

**Comment by edmondchuc** [comment]
Cool thanks.

@junrongYu Currently both slope and aspect are defined twice in separate files under `vocab_files/attribute_concepts` and `vocab_files/observable_property_concepts`. We need to decide when a concept is both an attribute and a concept, which duplicate should be deleted.

For example, we delete the file in `vocab_files/attribute_concepts` and keep the other one but we ensure the concept is a `skos:member` in all the necessary collections.

**Comment by junrongYu** [comment]
@edmondchuc , in this case, I prefer to delete the one under `vocab_files/attribute_concepts` because it is mostly a property except in `Camera traps`, and add `Camera traps` in `tern:hasMethod`, is that okay?

And this query shows that they are the only 2 duplicates:
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select * {
    <https://linked.data.gov.au/def/test/dawe-cv/dba9fde2-34ba-4a1d-92e0-63846105fc87> skos:member* ?s .
    <https://linked.data.gov.au/def/test/dawe-cv/e8e10807-baea-4c9b-8d1c-d77ced9df1e9> skos:member* ?s .
    ?s skos:prefLabel ?label .
}
```

**Comment by edmondchuc** [comment]
Sounds good. 

> add Camera traps in tern:hasMethod

What do you mean by this?

**Comment by junrongYu** [comment]
They both have only 1 method - `Plot Description`, I am thinking about adding other methods like `Soils - plot soil description` and `Camera traps`. 

Is it unnecessary? because we'll add module specific information in separate files.

**Comment by edmondchuc** [comment]
I don't think we need to add `Camera traps` since it's not being recorded as an observation there. 

Is slope and aspect observable properties in `Soils - plot soil description`?

**Comment by junrongYu** [comment]
Yes, they are in `Plot Description`, `Soils - plot soil description`, and those 3 submodules in `Camera traps`.

**Comment by edmondchuc** [comment]
Ok, have `Plot Description` and `Soils - plot soil description` as methods on aspect and slope then.
