### ISSUE TITLE
Target survey - Fauna protocol should be `skos:Collection` not `skos:Concept`

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/dawe-rlp-vocabs#127]
See: https://linkeddata.tern.org.au/viewers/dawe-vocabs?uri=https://linked.data.gov.au/def/test/dawe-cv/7a628781-ffec-4db7-ba58-214624365d82

**Comment by edmondchuc** [comment]
https://github.com/ternaustralia/dawe-rlp-vocabs/issues/128

**Comment by junrongYu** [comment]
It's done during methods vocabulary improvement.
