### ISSUE TITLE
Add metadata for each observable property for each protocol its feature type, value type, etc.

### ISSUE THREAD

**Issue by edmondchuc** [ternaustralia/dawe-rlp-vocabs#133]
See https://github.com/ternaustralia/dawe-rlp-vocabs/pull/131#issuecomment-1175737611

Proposal:

- A file per protocol containing the metadata
- Location of files goes in `vocab_files/observable_properties_by_module`

Each observable property for each protocol contains the following shape:

```turtle
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

<https://linked.data.gov.au/def/nrm/c9491ae2-43aa-47d8-acf6-5373ff49df6d> a <urn:class:ObservablePropertyMeta> ;
    <urn:property:protocolModule> <https://linked.data.gov.au/def/test/dawe-cv/1ff9e97c-3bdd-44c9-bdd3-401fa31c0b32> ;
    <urn:property:observableProperty> <https://linked.data.gov.au/def/test/dawe-cv/132a1452-4fd7-473c-956b-3183dd315b67> ;
    <urn:property:featureType> <http://linked.data.gov.au/def/tern-cv/2cf3ed29-440e-4a50-9bbc-5aab30df9fcd> ;
    <urn:property:valueType> <https://w3id.org/tern/ontologies/tern/IRI> ;
    <urn:property:categoricalValuesCollection> <https://linked.data.gov.au/def/test/dawe-cv/d893e669-c530-4bc3-a057-a5799ffcb5db> ;
   schema:url "https://github.com/ternaustralia/dawe-rlp-vocabs/tree/main/vocab_files/observable_properties_by_module/plot-description/slope-class.ttl"^^xsd:anyURI ;
.
```

We currently use URNs for the classes and properties. Later once the structure is stable, we can implement it in a proper namespace.

**Comment by junrongYu** [comment]
Hi @edmondchuc , should we use this structure if one property has multiple methods but the same feature type, value type and categorical collection?

**Comment by edmondchuc** [comment]
Yes, we need one for each observable property and protocol regardless if some of the other values are the same or not.

**Comment by junrongYu** [comment]
Sounds cool, where can we put these files in?
The mentioned folder `vocab_files/observable_property_metadata`, and create one Turtle file for each;
Or inside each property Turtle file? Or in each `collection.ttl` for modules.

**Comment by edmondchuc** [comment]
Yeah I like the idea to put it in `vocab_files/observable_property_by_module`

E.g.
```
vocab_files/
├─ observable_property_by_module/
│  ├─ basal-area/
│  │  ├─ collection.ttl
│  │  ├─ basal-area-count.ttl
│  │  ├─ basal-area-sweep-hit-type.ttl
```

The files `basal-area-count.ttl` and `basal-area-sweep-hit-type.ttl` describes the feature type, value type etc of the observable property in the basal area protocol.

**Comment by edmondchuc** [comment]
Edit: Updated opening post adding `schema:url` usage.

**Comment by edmondchuc** [comment]
What do you mean only implement for common parameters? What about the other ones that are not common?

**Comment by junrongYu** [comment]
If the property is not common, then we don't create meta Turtle file for it, so it is not the object of `<urn:property:observableProperty>`, then the website fetches the property directly and present it.
If it's common, we have meta Turtle file for it, so it's the object of `<urn:property:observableProperty>`, in this case, the website fetches module specific information and present the property differently in each module.

I am not sure if it's possible to do so in `linkeddata-site`.

**Comment by edmondchuc** [comment]
It is simpler and easier to maintain if all of that information is following the same pattern rather than having this conditional thing. Let's put everything as separate files whether they are common or not, otherwise there will be complicated logic in the frontend and we have to query the database multiple times.

**Comment by edmondchuc** [comment]
Yes please.

**Comment by junrongYu** [comment]
Can I solve these issues first?
#104 
#105 
#106

**Comment by edmondchuc** [comment]
Yeah, sounds good!

**Comment by junrongYu** [comment]
Hi @edmondchuc , do we need to differentiate `dcterms:source`, `schema:url`, and `tern:hasMethod` as well?

For `dcterms:source`:
If a property is common, then in each Turtle file for each module, the file name in source is different. Like for `coarse woody debris count (cwd count)`, it exists in 2 submodules under `CWD`, so sources are `Ecological Field Monitoring protocols - Coarse woody debris - Plots measures protocol, draft v0.1, 30/11/2021` and `Ecological Field Monitoring protocols - Coarse woody debris - Transects measures protocol, draft v0.1, 30/11/2021`.

`schema:url` has 2 values:
One for property general information - `https://github.com/ternaustralia/dawe-rlp-vocabs/tree/master/vocab_files/observable_property_concepts/coarse-woody-debris-count-(cwd-count).ttl`
One from module specific Turtle file - `https://github.com/ternaustralia/dawe-rlp-vocabs/tree/master/vocab_files/observable_properties_by_module/coarse-woody-debris/plot-measures-protocol/coarse-woody-debris-count-(cwd-count).ttl`

`tern:hasMethod`:
The value is also module specific.

**Comment by junrongYu** [comment]
Discussion from Friday's catch up: `dcterms:source` can be added in methods; `schema:url` unnecessary; **`tern:hasMethod` should be module specific**.

**Comment by junrongYu** [comment]
The feature type of some parameters may be updated from https://github.com/ternaustralia/dawe-rlp-vocabs/issues/139
