### ISSUE TITLE
Review source, definition, and feature type for parameters

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#139]
The definition source for some parameters are from existing parameters in `tern_vocabs_core`, previously replaced by protocol file name, but should use the original link. 

All sources with URL values should add the datatype `xsd:anyURI`.

Add `dcterms:source` for each method, and the value is the protocol manual.

**Comment by junrongYu** [comment]
During Monday's project meeting, Guru suggested that the source, definition and feature type of parameters should be reviewed after Arun finished work about `interventions`. Here some unsolved related issues from synonyms task will be recorded.

**Comment by junrongYu** [comment]
The comment in `growth stage` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/204#issuecomment-1234948687

**Comment by junrongYu** [comment]
The comment in `growth form` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/205#issuecomment-1237543438

**Comment by junrongYu** [comment]
Comments from `habitat description` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/206#issuecomment-1235051522 & https://github.com/ternaustralia/dawe-rlp-vocabs/pull/206#issuecomment-1237532479

**Comment by junrongYu** [comment]
The comment from `lithology type` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/209#issuecomment-1237544380

**Comment by junrongYu** [comment]
Comments for `voucher specimen` related attributes: https://github.com/ternaustralia/dawe-rlp-vocabs/pull/210#issuecomment-1237579095 & https://github.com/ternaustralia/dawe-rlp-vocabs/pull/210#issuecomment-1237579701

**Comment by junrongYu** [comment]
The comment for `vegetation health` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/212#issuecomment-1237678795

**Comment by junrongYu** [comment]
The comment for `plant status` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/213#issuecomment-1237807097

**Comment by junrongYu** [comment]
The value type for `plant status` need to be confirmed. https://github.com/ternaustralia/dawe-rlp-vocabs/pull/213#issuecomment-1237810550

**Comment by junrongYu** [comment]
The comment from `in-canopy sky` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/209#issuecomment-1238807861

**Comment by junrongYu** [comment]
The comment from `plant height` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/215#issuecomment-1238902326

**Comment by junrongYu** [comment]
The comment from `sex` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/216#issuecomment-1238923187

**Comment by junrongYu** [comment]
The comment from `plant phenology` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/223#issuecomment-1240189616

**Comment by junrongYu** [comment]
The comment from `disturbance` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/224#issuecomment-1240211020

**Comment by edmondchuc** [comment]
@junrongYu these can be consolidated into the opening post of this issue as checkboxes rather than individual separate comments.

E.g.

- [ ] `plant phenology` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/223#issuecomment-1240189616

**Comment by junrongYu** [comment]
Comments to be confirmed:
- [ ] `growth stage` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/204#issuecomment-1234948687
- [ ] `growth form` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/205#issuecomment-1237543438
- [ ] `habitat description` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/206#issuecomment-1235051522 
- [ ] `habitat description` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/206#issuecomment-1237532479
- [ ] `lithology type` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/209#issuecomment-1237544380
- [ ] `voucher specimen` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/210#issuecomment-1237579095 
- [ ] `voucher specimen` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/210#issuecomment-1237579701
- [ ] `vegetation health` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/212#issuecomment-1237678795
- [ ] `plant status` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/213#issuecomment-1237807097
- [ ] `in-canopy sky` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/209#issuecomment-1238807861
- [ ] `plant height` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/215#issuecomment-1238902326
- [ ] `sex` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/216#issuecomment-1238923187
- [ ] `plant phenology` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/223#issuecomment-1240189616
- [ ] `disturbance` https://github.com/ternaustralia/dawe-rlp-vocabs/pull/224#issuecomment-1240211020
