### ISSUE TITLE
Replace `Plot description` in `Soil Attributes` with `plot location description` 

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#15]
`plot location description` is different from `Plot description`, and it makes more sense in this context.
Replaced already in the spreadsheet, but forgot to updated in Google drive, will be fixed when migration finished.

**Comment by edmondchuc** [comment]
From meeting: fine to go with plot location description

**Comment by edmondchuc** [comment]
Go with soil sampling location description
