### ISSUE TITLE
Change `animal teats condition`, `teat status` to `fauna teat condition`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#17]
`animal teats condition` and `teat status` are the same, Arun prefers the label `fauna teat condition`. There are 2 different categorical APIs, and will use the api with definition for each value http://vocabs.paratoo.tern.org.au:1337/api/lut-fauna-teats-conditions

**Comment by edmondchuc** [comment]
From meeting: use teat status
