### ISSUE TITLE
Added the attribute "general project information" in "intervention module- field collection"

### ISSUE THREAD

**Issue by arunherb** [ternaustralia/dawe-rlp-vocabs#189]
There is an attribute called "**general project information**", which is a text field that needs to be captured under the "**Intervention module- field collection"**
The definition based on the module is "Any relevant comments/notes on the intervention activity. "
Ref: Kimberly McCallum's comments: " This will allow users to record basic project information, such as general notes about the interventions to be undertaken, any locations targeted and details about who is undertaking the work. Multiple intervention areas can be added on the following screen and will all be linked to this general overview."

**Comment by junrongYu** [comment]
Done, the attribute is added.
