### ISSUE TITLE
Update protocol and synonyms for intervention module

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#207]
To review intervention module updated by Kimberly for TDDP protocols page. Identify key synonyms and protocol mapping related issues will be documented here.

**Comment by arunherb** [comment]
@junrongYu - 
I'll document all the protocol mapping requirements with my comments in this page : https://docs.google.com/document/d/1mbnIY76hrcm1Ez36SVoTT9LGtUUEond3/edit 
And, the vocabs and synonyms related to this module in this spreadsheet: https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=1709262829

Thanks
Arun

**Comment by arunherb** [comment]
@junrongYu ,
Here are some updates:
1) Make the vocab "general project information" a text field. This has already been documented here : https://github.com/ternaustralia/dawe-rlp-vocabs/issues/189#issue-1325202071
2) In the spreadsheet, I've highlighted sub-modules in various colours, i.e., green colour is part of the intervention activity; yellow colour is partial and therefore not required to be captured as part of intervention activity as suggested by Kimberley in their updated protocol document.
3) Under the sub-module "**controlling pest animals**": 
a) I've replaced the vocab: "_controlling pest activity type_" to "_pest control activity type_" and it is a boolean (i.e., initial or follow-up).; b) I've replaced the vocab: "_pest control type_" to "_type of pest control_" and " type of pest control - other".

**Comment by arunherb** [comment]
Hi @edmondchuc ,

Here's a general overview of what the _Intervention module_ is like:

So, we have 

1) **Type of _Intervention activity_** - which is a sub-module in appendix-1

2) The activity can be sub classified as : 
a) Activity related to **management action**; b) Activity related to **conducting survey/s**;   

3) An **attribute** of the activity- such as the location/sites, date range, number of structures installed and/or maintained, target species/individuals managed etc. 
4) Each of the above attributes may or may not be associated with a '**feature type**' (e.g. 'site' or 'subsite' is a feature of the location).
5) An **outcome/result** of an intervention activity - such as 'the number of breeding programs managed/monitored', 'number of animal pests eliminated', 'total number of weeds removed' (in terms of area/mass), 'plant survival rate' due to intervention, 'areas benefitted due to the activity' etc.

This is just a break-up of what's happening in the module. Not sure how you'd want to capture this in the TERN model.
See if it helps us brainstorm in upcoming meetings and we can build from thereon. 

I'm documenting the mapping based on what we received from Kimberley. 
I'll comment in this page, as and when I come-up with striking features of this module. 

Thanks and hope it helps.
Arun

**Comment by arunherb** [comment]
Hi @edmondchuc ,

Here are some updates for the interventions module:
1) see these comments :https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1236435580; https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1236455074
2) There is a column in the appendix -1 of intervention module that lists "mapping requirements" and "mapping area". Not sure how you would want to capture this in your information model. Do you want you create a column for them in the spreadsheet?
3) Under the sub-module "Establishing and maintaining breeding program", we have a vocab, "target threatened species". Do you know what would be the feature type- because the species may be a 'flora' or 'fauna'
4)At the moment I've put all the vocabs under the attributes column. We should brainstorm and see what would be the best choice for them once we have the mapping clarified. 
5) Under sub-module " Undertaking Emergency Intervention", there is "target species"- the problem here is the same as point number 3. It can be a feature of plant or animal occurrence. 

Thanks
Arun

**Comment by arunherb** [comment]
Definitions for Intervention module have been updated : https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=1203860376
See the attributes definition sheet

Arun

**Comment by arunherb** [comment]
hi @junrongYu ,

I've updated the Intervention module for mapping. 
https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=0 

Let me know if you have any questions.

Thank you,
Arun

**Comment by junrongYu** [comment]
Hi @arunherb ,

Could you add the feature type for these properties?

    "Intervention module- Controlling access : number of structures installed",
    "Intervention module- habitat augmentation : number of structures installed",
    "Intervention module-Improving hydrological regime : number of treatments implemented",
    "Intervention module - Plant survival survey : number of plant survival surveys",
    "Intervention module- Remediating riparian and aquatic area : number of structures installed",
    "Intervention module- Revegetating habitat : seed collection days",
    "Intervention module- Revegetating habitat : plant propagation days",
    "Intervention module- soil testing : number of soil tests conducted",
    "Intervention module- Undertaking emergency interventions to prevent extinctions : number of emergency interventions",
    "Intervention module- Water quality survey : number of water quality surveys",
    "Intervention module- weed distribution survey : number of weed distribution surveys",

Thanks,
Junrong

**Comment by junrongYu** [comment]
Hi @arunherb , 

Could you please clarify property `number of water quality surveys`? The label is different in `Observable Properties-definition`, it's `number of water quality surveys conducted`.

Thanks,
Junrong

**Comment by junrongYu** [comment]
We don't have categorical values for categorical parameter `target threatened species`.
![Screen Shot 2022-09-15 at 1 54 41 pm](https://user-images.githubusercontent.com/99153064/190310213-add9141a-5406-4c0d-9901-71eb455c6495.png)

**Comment by junrongYu** [comment]
Hi @arunherb ,

I am thinking the value type for those `date range` attributes is `text` instead of `date`? because the protocol says `Free text`.
![Screen Shot 2022-09-15 at 2 14 05 pm](https://user-images.githubusercontent.com/99153064/190312669-ec560b2c-a040-45c1-a45f-0fbe2f1b37dc.png)

**Comment by junrongYu** [comment]
Hi @arunherb ,

For properties `pest control area- initial` and `pest control area- follow-up`, I am wondering whether they are `Boolean`? the pest control area is either initial or follow up? Or we can use one property `pest control area` and it's categorical with values `initial` and `follow-up`.

![Screen Shot 2022-09-15 at 2 25 51 pm](https://user-images.githubusercontent.com/99153064/190314245-6b8fa34e-e470-4da4-97fe-5a5f9b3079ae.png)

**Comment by junrongYu** [comment]
Hi @arunherb ,

In the module `Intervention module- Removing weeds`, line 385 in the spreadsheet, property `weed removal area- initial` and attribute `area treated for weed removal` are in the same line, so I am not sure which parameter the row info is for.

**Comment by junrongYu** [comment]
Hi @arunherb , 

The issue for properties `habitat revegetation area- initial` and `habitat revegetation area- maintained` is the same as https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1247566188.

It's categorical from the protocol
![Screen Shot 2022-09-15 at 2 50 10 pm](https://user-images.githubusercontent.com/99153064/190317131-2c8d8b4e-6912-44e1-a214-2e2ba05ad605.png)
However, currently we don't have this categorical API, do you think it's better to ask for API or we change the value type to `Boolean`?

Thanks,
Junrong

**Comment by junrongYu** [comment]
Hi @arunherb ,

Maybe we need to discuss with Guru and Edmond about what value type is suitable for parameters in https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1247566188 & https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1247579968, also for attribute `weed distribution survey type` in weed distribution survey.

`boolean` or `categorical`, or we can create 2 parameters for each value, and the value type is boolean.

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> For properties `pest control area- initial` and `pest control area- follow-up`, I am wondering whether they are `Boolean`? the pest control area is either initial or follow up? Or we can use one property `pest control area` and it's categorical with values `initial` and `follow-up`.
> 
> ![Screen Shot 2022-09-15 at 2 25 51 pm](https://user-images.githubusercontent.com/99153064/190314245-6b8fa34e-e470-4da4-97fe-5a5f9b3079ae.png)

Hi @junrongYu ,

I think it is just pest control area. It is an observable property. There is no "initial' or "follow-up". That belongs to the "pest control activity type". I've update the same on the Spreadsheet.

Thank you
Arun

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> Could you add the feature type for these properties?
> 
> ```
> "Intervention module- Controlling access : number of structures installed",
> "Intervention module- habitat augmentation : number of structures installed",
> "Intervention module-Improving hydrological regime : number of treatments implemented",
> "Intervention module - Plant survival survey : number of plant survival surveys",
> "Intervention module- Remediating riparian and aquatic area : number of structures installed",
> "Intervention module- Revegetating habitat : seed collection days",
> "Intervention module- Revegetating habitat : plant propagation days",
> "Intervention module- soil testing : number of soil tests conducted",
> "Intervention module- Undertaking emergency interventions to prevent extinctions : number of emergency interventions",
> "Intervention module- Water quality survey : number of water quality surveys",
> "Intervention module- weed distribution survey : number of weed distribution surveys",
> ```
> 
> Thanks, Junrong

Hi @junrongYu ,

The feature types for some of them are quite tricky. We need to discuss during our weekly meeting for choosing an appropriate feature type for each of the property listed. At the moment the closest available feature type on the drop-down list is "administrative area". We should probably have a feature called "intervention activity" itself! Lets see how we go.

Arun

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> Could you please clarify property `number of water quality surveys`? The label is different in `Observable Properties-definition`, it's `number of water quality surveys conducted`.
> 
> Thanks, Junrong

Hi @junrongYu ,

I've updated it to just "number of water quality surveys"

Arun

**Comment by arunherb** [comment]
> We don't have categorical values for categorical parameter `target threatened species`. ![Screen Shot 2022-09-15 at 1 54 41 pm](https://user-images.githubusercontent.com/99153064/190310213-add9141a-5406-4c0d-9901-71eb455c6495.png)

We should ask Sally's team what are those. I would imagine them to be a red list of plant or animal species from the survey area. 

Arun

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> I am thinking the value type for those `date range` attributes is `text` instead of `date`? because the protocol says `Free text`. ![Screen Shot 2022-09-15 at 2 14 05 pm](https://user-images.githubusercontent.com/99153064/190312669-ec560b2c-a040-45c1-a45f-0fbe2f1b37dc.png)

Updated to "text". Thanks for that.

Arun

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> In the module `Intervention module- Removing weeds`, line 385 in the spreadsheet, property `weed removal area- initial` and attribute `area treated for weed removal` are in the same line, so I am not sure which parameter the row info is for.

Hi @junrongYu ,

This must be an entry error. I've updated this based on the protocol. Thanks for checking.
Arun

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> Maybe we need to discuss with Guru and Edmond about what value type is suitable for parameters in [#207 (comment)](https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1247566188) & [#207 (comment)](https://github.com/ternaustralia/dawe-rlp-vocabs/issues/207#issuecomment-1247579968), also for attribute `weed distribution survey type` in weed distribution survey.
> 
> `boolean` or `categorical`, or we can create 2 parameters for each value, and the value type is boolean.

Hi @junrongYu ,

For "habitat revegetation type", I have updated it to "habitat revegetation activity type" to be more specific.  It looks like a categorical drop-down for "initial" or "maintained". So, for instance if the activity type is "maintained", then the "habitat revegetation area - maintained" will be followed during the survey. I've also updated "habitat revegetation area - initial" to just "habitat revegetation area" based on the module.

For `weed distribution survey type` , it is also a categorical with those drop-down mentioned. 
We can anyways discuss with the DAWE team to see what everyone thinks.

Thank you,
Arun

**Comment by junrongYu** [comment]
Done, intervention parameters finalised.
