### ISSUE TITLE
Change `health`, `flora health factor`, `health factors`, `vegetation health` to `vegetation health factor`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#26]
These 4 parameters are the same, with the same definition and categorical values. We decided to use `vegetation health factor` as the new label.

Also, the new definition for `vegetation health factor` should be used.

Still need to decide which categorical API to use. #27 

Steps (for TDSA):

Update `flora health factor` to `vegetation health factor`;
Change the definition to `The visible factors affecting the vegetation health while assessing the condition of the sampling vegetation. Examples factors include: Canopy health, Mistletoe, Epicormic growth, Galls and lerps, Dieback from disease, and Grazing.`;
Add feature type `plant community`;
Add additional methods:
    `Targeted survey module - Flora protocol - Population`
    `Recruitment module -Survivorship protocol`
    `Targeted survey module - Ecological Community protocol`
    `Condition`
Fix syntax error in source;
Replace URIs in the following properties collection:
    `Recruitment module -Survivorship protocol`
    `Targeted survey module - Ecological Community protocol`
    `Condition`
Delete properties `vegetation health`, `health factors`, `health`;
Normalize all files and test them locally.

**Comment by junrongYu** [comment]
Hi @arunherb , can you run this query to see which feature type is the most suitable for this property?

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?moduleCollectionLabel ?parameterLabel ?parameterDefinition ?valueType ?featureType ?parameterMethod ?parameterSource ?categoricalCollectionLabel ?api
{
    ?moduleCollectionURI skos:member ?parameterURI ;
                         skos:prefLabel ?moduleCollectionLabel .
    ?parameterURI skos:prefLabel ?parameterLabel ;
    				tern:valueType ?valueTypeURI .
    ?valueTypeURI rdfs:label ?valueType .
    optional {?parameterURI skos:definition ?parameterDefinition .}
    optional {
            ?parameterURI tern:hasFeatureType ?featureTypeURI . 
            service <https://graphdb.tern.org.au/repositories/tern_vocabs_core> {
        ?featureTypeURI skos:prefLabel ?featureType .
    }}
    optional {
        ?parameterURI tern:hasMethod ?parameterMethodURI .
        ?parameterMethodURI skos:prefLabel ?parameterMethod .
    }
    optional {
        ?parameterURI dcterms:source ?parameterSource .
    }
    optional {
        ?parameterURI tern:hasCategoricalCollection ?categoricalCollectionURI .
        ?categoricalCollectionURI skos:prefLabel ?categoricalCollectionLabel ;
                                  dcterms:source ?api .
    }
    filter (?parameterLabel in ('health', 'flora health factor', 'health factors', 'vegetation health'))
}
order by ?parameterLabel
```

**Comment by arunherb** [comment]
Hi Jun,
I think the 'flora health factors', 'vegetation health', 'health' and 'health factors' have the common categorical API's. I would just collapse these into one common parameter called 'vegetation health factors'.

**Comment by arunherb** [comment]
For feature types:
1) "vegetation health factor" for Targeted survey use "plant individual" as feature type.
2) "vegetation health factor" for Targeted Ecological Community, use "plant community" as feature type.
3) "vegetation health factor" for Condition module, use "plant individual" as feature type.
