### ISSUE TITLE
Integrate `replicate count` and `replicate number`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#285]
`replicate count` is an attribute from `plot selection`, `replicate number` is an attribute from `vertebrate`. Arun said they are the same attribute so should be consistent across all modules.

**Comment by arunherb** [comment]
I'd keep 'replicate number'- as it is not a count and "Plot replication number" has been used to define 'replicate count'.

**Comment by junrongYu** [comment]
> I'd keep 'replicate number'- as it is not a count and "Plot replication number" has been used to define 'replicate count'.

Thanks Arun, which `Plot replication number` are you referring to? If `replicate number` is used to define `replicate count`, does that mean they are different and both should be kept?

Thanks,
Junrong

**Comment by arunherb** [comment]
> > I'd keep 'replicate number'- as it is not a count and "Plot replication number" has been used to define 'replicate count'.
> 
> Thanks Arun, which `Plot replication number` are you referring to? If `replicate number` is used to define `replicate count`, does that mean they are different and both should be kept?
> 
> Thanks, Junrong

Hi Jun,

I guess this has to be just one vocab called 'replicate number'. There is no vocab called 'replicate count' in the plot selection and layout module. 
Arun
