### ISSUE TITLE
Delete redundant definition for `plot orientation`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#30]
`plot orientation` has 2 definitions
`The direction or orientation the plot (as a standard the plot alighs in the NS direction of the grid).`
&
`The orientation of the plot.`
The second one is not meaningful and redundant, should be deleted.

**Comment by smguru** [comment]
@junrongYu  do we have 2 different concepts?

**Comment by junrongYu** [comment]
> @junrongYu do we have 2 different concepts?
hi @smguru , only one concept and it has 2 definitions.
