### ISSUE TITLE
Replace `plot type` in `Vertebrate fauna module- Fauna plot layout and photographs protocol` with `impact plot` and `control plot`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#31]
`impact plot` and `control plot` will be selected in this module as well, they are `Boolean` values so themselves can show the `plot type`. Therefore, `plot type` is redundant. the URI of `impact plot` and `control plot` will be added to the collection URI for `Vertebrate fauna module- Fauna plot layout and photographs protocol Attributes`.

**Comment by edmondchuc** [comment]
From meeting: may not need to be referenced in the module anymore. This is not required anymore.
