### ISSUE TITLE
[Protocol issue] Floristics

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#51]
Description TBD with Arun.
Jira task: https://ternaus.atlassian.net/browse/TERNDA-3910?atlOrigin=eyJpIjoiNDBmMzk5ZDBkZjU0NGE1YWE3NTVjYjFjMmIwODc2NDgiLCJwIjoiaiJ9

**Comment by smguru** [comment]
@junrongYu not sure what the issues are, there is not point in putting a place holder. You can create an issues when something is identified.

**Comment by junrongYu** [comment]
> @junrongYu not sure what the issues are, there is not point in putting a place holder. You can create an issues when something is identified.

hi @smguru , yes, the description will be updated when we start fixing this method.

**Comment by junrongYu** [comment]
> @junrongYu not sure what the issues are, there is not point in putting a place holder. You can create an issues when something is identified.

hi @smguru , these issues are created because we want to manage all issues on Github. Later when I've updated methods, this issue can be tagged, like this PR #96 , so we know that this issue is resolved.
