### ISSUE TITLE
Finalise values for `fauna survey technique` and `flora survey technique` in `intervention` module

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#52]
Values for these 2 parameters are currently `Free Text -300`, waiting for protocols team to finalise methods.

-----------------

From Trello https://trello.com/c/diArcvFN

**Comment by edmondchuc** [comment]
From meeting: leave it as free text

**Comment by junrongYu** [comment]
The `Fauna survey` and `Flora survey` section in `Intervention` are not captured in CV now, so it is not compulsory to add them.
