### ISSUE TITLE
Change `animal behaviour`, `behaviour` to `fauna behaviour`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#63]
`animal behaviour` from `Opportunistic` and `behaviour` from `Vertebrate fauna module - Active and passive searching protocol` have the same definition, feature type, value type, source, and categorical values. Therefore, they are the same property, then use `fauna behaviour` as new label. 

The `behaviour` can be deleted, then add the URI of `animal behaviour` to the `vertebrate` properties collection.

**Comment by edmondchuc** [comment]
From meeting: go with fauna behaviour
