### ISSUE TITLE
Remove redundant date time parameters

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#69]
There are 31 date time parameters in DAWE vocabulary, but some can be replaced by TERN Ontology classes (`end search` can be `prov:endedAtTime`), some cannot (`search time` - it is a duration parameter). We are not sure which one protocols team want to preserve.

Here all date time parameters can be fetched by the following steps:

1. Open https://graphdb.tern.org.au/
2. Select repository as `dawe_vocabs_core`
![Screen Shot 2022-06-21 at 11 01 52 am](https://user-images.githubusercontent.com/99153064/174695186-5f6b015e-13ef-4c2a-8d67-9bc2dff3a80d.png)
3. At the left-hand side category, select `SPARQL`
4. Run the query

```
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select ?moduleLabel ?parameterLabel ?definition ?type {
    ?module skos:member ?parameter ;
            skos:prefLabel ?moduleLabel .
    ?parameter tern:valueType ?type ;
               skos:prefLabel ?parameterLabel ;
				skos:definition ?definition .
    filter (?type in (tern:DateTime, tern:Date))
}
order by ?parameterLabel
```

There are some duplicated parameters in the result because they are used in different modules or submodules. 
1st column shows which module this parameter belongs to, e.g. `Fire Attributes` means the parameter is in the protocol `Fire`.
2nd column is the parameter name, 3rd column is the parameter definition, 4th column is the parameter type, `Date` or `DateTime`.

`Date` is https://linkeddata.tern.org.au/viewers/tern-ontology?uri=https://w3id.org/tern/ontologies/tern/Date
`DateTime` is https://linkeddata.tern.org.au/viewers/tern-ontology?uri=https://w3id.org/tern/ontologies/tern/DateTime

**Comment by edmondchuc** [comment]
From meeting: use prov start and end time properties

duration - do we really need it since we already know the start and end time

**Comment by junrongYu** [comment]
This is the list of date time attributes:



parameterLabel | definition | type
-- | -- | --
**accuracy of the fire** | Accuracy of fire event is an estimate of the time and date accuracy of the fire event, which is normally an estimate and/or cited from the most reliable source/s. It can range from hours to days to months or years. | tern:DateTime
camera settings- datetime | The date and time of the image captured. | tern:DateTime
date of light trap removal | The date of removal of the light traps. | tern:Date
date of pan trap establishment | The date of pan trap establishment. | tern:Date
datetime | The date and time of the active search of invertebrate sampling (auto recorded). | tern:DateTime
deployment date | The date of deployment of the camera traps. | tern:Date
end search | The date and time of the end of active search of invertebrate fauna. | tern:DateTime
equipment check datetime | The date and time (autorecorded) while conducting the equipment check. | tern:DateTime
equipment setup datetime | The date and time of the trap/equipment being set-up (autorecorded), during a passive- targeted fauna survey. | tern:DateTime
leaf-litter sampling date | The date of leaf-litter sampling | tern:Date
leaf-litter sampling time | The time of leaf-litter sampling | tern:DateTime
litter extraction end date | The end date of leaf litter extraction. To record how long the sample was dried. | tern:Date
litter extraction end time | The end time of leaf litter extraction. To record how long the sample was dried. | tern:DateTime
malaise trap set-up date | The malaise trap set-up date. | tern:Date
malaise trap set-up time | The malaise trap set-up time. | tern:DateTime
new sample collection date | An auto record of the sample collection date, when the new sample collection bottle is replaced during malaise trapping - invertebrate fauna survey. | tern:Date
new sample collection time | An auto record of the sample collection time, when the new sample collection bottle is replaced during malaise trapping - invertebrate fauna survey. | tern:DateTime
observation datetime | The date and time when observation/s were made. | tern:DateTime
pan trap removal date | The date of removal of the pan traps from study sites. | tern:Date
pan trap removal time | The time of removal of pan traps from the study sites. | tern:DateTime
pan trap sample collection date | The date of pan trap sample collection. | tern:Date
pan trap sample collection time | The time of pan trap sample collection. | tern:DateTime
recovery date | The date when the camera trap/s were recovered from the study site. | tern:DateTime
redeployment date | The date when the camera traps were redeployed. | tern:DateTime
**search time** | The standard ort minimum time taken to search for invertebrates (active search is usually 60 minutes). | tern:DateTime
start search | The date and time of the start of active search of invertebrate fauna. | tern:DateTime
survey start datetime | The date and time of the start of a survey. | tern:DateTime
survey start time | The start time of the targeted survey. | tern:DateTime
**time of light trap removal** | The time of removal of the light traps. | tern:DateTime
**time of pan trap establishment** | The time of pan trap establishment. | tern:DateTime
**time since fire** | The amount of time passed since the first fire event or start date and time of the fire event has occurred. | tern:DateTime

Hi @edmondchuc , could you please have a look at the above table? Here, all the data and time related attributes are listed and I think all of them can be replaced by `prov` start and end time properties, except for those bold one.

**Comment by edmondchuc** [comment]
Hi @junrongYu, `prov:startedAtTime` and `prov:endedAtTime` are the date time values of the start and end of activities. Therefore, I think it's only applicable to the ones such as "survey start datetime" and "survey start time". The other ones like "recovery date" and "date of pan trap establishment" I think are not applicable.

**Comment by junrongYu** [comment]
Hi @edmondchuc ,thanks! How about these attributes, are they like start and end time?


datetime | The date and time of the active search of invertebrate sampling (auto recorded). | tern:DateTime
-- | -- | --


leaf-litter sampling date | The date of leaf-litter sampling | tern:Date
-- | -- | --
leaf-litter sampling time | The time of leaf-litter sampling | tern:DateTime


observation datetime | The date and time when observation/s were made. | tern:DateTime
-- | -- | --

**Comment by edmondchuc** [comment]
Yeah they look suitable.

**Comment by junrongYu** [comment]
Cool thanks! For these attributes, do we just delete them all?

**Comment by edmondchuc** [comment]
I think so, as long as we don't lose information. For example, the first one, `datetime - The date and time of the active search of invertebrate sampling (auto recorded).`, in a `Sampling` activity, we specify the start and end time with `prov:startedAtTime` and `prov:endedAtTime` and for the "active search of invertebrate sampling" part, we express that by linking to the correct method via the property `sosa:usedProcedure`. So looks like should be fine to delete them since all the information will be retained properly.

**Comment by junrongYu** [comment]
> and for the "active search of invertebrate sampling" part, we express that by linking to the correct method via the property sosa:usedProcedure

Hi @edmondchuc , will `sosa:usedProcedure` be designed in the App? Or should we add it to our vocabulary now? like add it to the attribute or property concept, metadata for properties etc.

**Comment by edmondchuc** [comment]
If you look at [`tern:Sampling`](https://w3id.org/tern/ontologies/tern/Sampling) or [`tern:Observation`](https://w3id.org/tern/ontologies/tern/Observation), you will see there's a property on the class called `sosa:usedProcedure`. This is defined in SOSA, see https://www.w3.org/TR/vocab-ssn/#SOSAusedProcedure.

**Comment by junrongYu** [comment]
> If you look at [`tern:Sampling`](https://w3id.org/tern/ontologies/tern/Sampling) or [`tern:Observation`](https://w3id.org/tern/ontologies/tern/Observation), you will see there's a property on the class called `sosa:usedProcedure`. This is defined in SOSA, see https://www.w3.org/TR/vocab-ssn/#SOSAusedProcedure.

Thanks! I understand now. I'll delete these attributes.

**Comment by junrongYu** [comment]
Attributes to be deleted:

`datetime`, `end search`, `leaf-litter sampling date`, `leaf-litter sampling time`, `observation datetime`, `start search`, `survey start datetime`, `survey start time`.
