### ISSUE TITLE
Are these 3 `disturbance` the same?

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#71]
There are 3 different `disturbance` related parameters in DAWE vocabulary, and they are using the same categorical API http://vocabs.paratoo.tern.org.au:1337/api/lut-disturbances

1. `disturbance` from last deliverable, in modules `Plot Description` and `Vegetation Mapping`. 
The definition is `Evidence of anthropogenic disturbance at a site. These include grazing,  clearing and land-use change.`
Description from protocol files is:
![Screen Shot 2022-06-21 at 12 04 54 pm](https://user-images.githubusercontent.com/99153064/174701170-18286eac-3902-4024-9886-612ddc06fbf9.png)
Categorical values from protocol file:
![Screen Shot 2022-06-21 at 12 06 32 pm](https://user-images.githubusercontent.com/99153064/174701319-14d964c4-a733-487a-ae04-c0304e65ecf2.png)

2. `disturbance` in module `Targeted survey module - Ecological Community protocol`.
The definition is `The disturbance factor (chosen from a drop-down list) indicating the level of disturbance of the targeted ecological community in study.`
Description from protocol file:
![Screen Shot 2022-06-21 at 12 09 13 pm](https://user-images.githubusercontent.com/99153064/174701595-f8e3ccc2-e710-4c21-b75c-9edd0b838ae4.png)
Categorical values not provided in the protocol file.

3. `land surface disturbance` in module `Soils - plot soil description`.
The definition is `A disturbance which occurs on the land surface, typically modifying the landscape including biological communities.`
Description from protocol file:
![Screen Shot 2022-06-21 at 12 15 27 pm](https://user-images.githubusercontent.com/99153064/174702157-f245bca7-09a1-4654-9493-e06a2531f1ea.png)
Categorical values from the protocol file:
![Screen Shot 2022-06-21 at 12 23 17 pm](https://user-images.githubusercontent.com/99153064/174702975-656d7592-32db-4fc3-af32-ff6af01131f0.png)

**Comment by edmondchuc** [comment]
From meeting: disturbance measures are the same across all modules

**Comment by edmondchuc** [comment]
Stick with the yellow book categorical values
