### ISSUE TITLE
Change `lepiled type` to `lepi-led type`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#74]
`lepi-led type` makes more sense. From the protocol file (invertebrate - light trapping): `This protocol uses a modern, LED light trap called LepiLED (https://www.gunnarbrehm.de/en/lepi-led), in conjunction with the LepiLED funnel and netting trap attachment.`

**Comment by edmondchuc** [comment]
From meeting: LepiLED type -
