### ISSUE TITLE
Change `notes` to `passive survey notes`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#76]
`notes` is an attribute in `Targeted survey module - Fauna protocol - Passive`, and its definition is `A free text summary of any notes relevant to the passive - targeted fauna survey.`. Therefore, we prefer the more specific label `passive survey notes`.

**Comment by edmondchuc** [comment]
From meeting: notes is fine - use it as the same across all modules
