### ISSUE TITLE
Are these 2 `phenology` the same?

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#79]
There are 2 `phenology` related parameters in DAWE vocabulary. They are created with different definitions and value types. We think they have the same feature type as `plant individual`, but not sure whether they are the same.

1. `phenology type` in `Opportunistic`, value type is `tern:IRI`, so it is categorical parameter.
The definition is `The peri­odical biological events of plants in relation to cli­mate and other environmental factors.`.
Description from the protocol file:
![Screen Shot 2022-06-21 at 4 13 16 pm](https://user-images.githubusercontent.com/99153064/174728854-377cccc7-2bf6-483e-bcbe-c8e09dd08c81.png)

2. `plant phenology` in `Invertebrate module- wet pitfall protocol`, value type is `tern:Text`.
The definition is `The study of the timing of recurring climate or weather-driven plant biological changes, the causes of periodicity, the relationship with biotic (e.g. fruit availability) and abiotic (e.g. rain) drivers and the interrelations between the seasonal cycle of the same or different species.`.
Description from the protocol file:
![Screen Shot 2022-06-21 at 4 15 21 pm](https://user-images.githubusercontent.com/99153064/174729174-c236151b-4677-400f-87ac-c90c427338f4.png)
![Screen Shot 2022-06-21 at 4 20 05 pm](https://user-images.githubusercontent.com/99153064/174729867-8d14e672-9729-410e-be11-a078369765f2.png)
![Screen Shot 2022-06-21 at 4 20 27 pm](https://user-images.githubusercontent.com/99153064/174729912-003014d2-9c95-4d79-a803-58c54ba37b56.png)
Categorical values not provided in the protocol file.

If they are the same, which label, definition, value type is better?

**Comment by edmondchuc** [comment]
From meeting: keep as plant phenology - go with definiton from invertebrates module - drop down
