### ISSUE TITLE
Change `photo direction` to `lepi-led photo direction`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#81]
`lepi-led photo direction` makes more sense. From the protocol file (invertebrate - light trapping): `This protocol uses a modern, LED light trap called LepiLED (https://www.gunnarbrehm.de/en/lepi-led), in conjunction with the LepiLED funnel and netting trap attachment.`

**Comment by edmondchuc** [comment]
From meeting: Keep as photo direction
