### ISSUE TITLE
Are these 2 `habitat` the same?

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#88]
There are 2 `habitat` related parameters in DAWE vocabulary:
`habitat description` in `Opportunistic Observations` and `Targeted survey`;
`habitat information` in `Invertebrate fauna`. 

They have similar definition and description in protocol files, but identified with different parameter types (attribute or property), labels, definitions, and value types.

Description of `habitat description`:
In `Opportunistic Observations`
![Screen Shot 2022-06-22 at 12 53 35 pm](https://user-images.githubusercontent.com/99153064/174933325-d50647e3-f8fc-4001-b575-d54d289f8837.png)
In `Targeted survey`
![Screen Shot 2022-06-22 at 12 55 48 pm](https://user-images.githubusercontent.com/99153064/174933618-c162c43a-db8b-4f1a-8e17-5d04c5af8e83.png)
![Screen Shot 2022-06-22 at 12 57 45 pm](https://user-images.githubusercontent.com/99153064/174933888-c239083a-2e82-442c-88ff-d7327224bf6b.png)
In `Invertebrate fauna`
![Screen Shot 2022-06-22 at 12 59 42 pm](https://user-images.githubusercontent.com/99153064/174934185-36b6f9a9-acc7-4b35-a962-33abbf91d837.png)

Categorical values for `habitat description`: http://vocabs.paratoo.tern.org.au:1337/api/lut-habitats

Description of `habitat information`:
In `Invertebrate fauna`
![Screen Shot 2022-06-22 at 1 10 54 pm](https://user-images.githubusercontent.com/99153064/174935328-17e9e0ee-52e1-4193-870a-ded759d92757.png)

If they are the same, is it attribute or property?

Which `label`, `definition`, `value type` can we use?

`label` options: `habitat description`, `habitat information`

`definition` options:

- An environmental system which can sustain and allow the growth of an ecological population.
- A brief description of the habitat where the survey is being conducted.
- A brief description of the habitat where invertebrates have been captured during active sampling.

`value type` options:

- `categorical`
- or `text`  (`or manual entry` mentioned)
- or both?

**Comment by j-robinson** [comment]
habitat description in targeted can align with opportune. In the invertebrate module, seems the habitat description is free text, so doesn't need to align.
