### ISSUE TITLE
`lut-recruitment-life-stages` VS `lut-condition-life-stages`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#89]
These 2 APIs have same values:
http://vocabs.paratoo.tern.org.au:1337/api/lut-recruitment-life-stages
http://vocabs.paratoo.tern.org.au:1337/api/lut-condition-life-stages
It would be better to replace them with `lut-life-stages` because it's more general.

**Comment by j-robinson** [comment]
They are the same, we have renamed one of them to `lut-flora-life-stage` and deleted the other.

**Comment by junrongYu** [comment]
> They are the same, we have renamed one of them to `lut-flora-life-stage` and deleted the other.

Hi @j-robinson , `lut-flora-life-stage` is not working, we'll use `lut-condition-life-stages`, could you left a comment here if something's updated?
