### ISSUE TITLE
Are `flora growth form` and `plant growth form` the same?

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#91]
TBC with Arun firstly.
`flora growth form` is a property in `Targeted survey`, and `plant growth form` is a property in `Fire`. They have the same definition but different categorical values.

**Comment by arunherb** [comment]
> TBC with Arun firstly. `flora growth form` is a property in `Targeted survey`, and `plant growth form` is a property in `Fire`. They have the same definition but different categorical values.

I think the "flora growth form", and 'plant growth form' are the same. The categorical values looks like they are just a variant- one is adopted from NSW Department of Planning 2020, and the other from NVIS Technical Working Group 2017? 
We need some clarity on this from the Surveillance team.

In addition, there is another vocab called "growth form (flora)" in the Opportunistic observation. It is nothing but "flora growth form" as per the drop-down categorical values.

Solution: we will keep 'flora growth form' for Opportunistic observation module and Targeted survey module, and we can use the "plant growth form" as preferred label in fire module and add "flora growth form" as "skos:altlabel"?
Does that help for now?

**Comment by junrongYu** [comment]
Hi @arunherb ,

> there is another vocab called "growth form (flora)" in the Opportunistic observation

I cannot see there is such a parameter here? https://linkeddata.tern.org.au/viewers/dawe-vocabs?uri=https://linked.data.gov.au/def/test/dawe-cv/d3f85cc2-f3e8-4900-a2ac-19fc27fd14f9

It's `growth form`.

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> > there is another vocab called "growth form (flora)" in the Opportunistic observation
> 
> I cannot see there is such a parameter here? https://linkeddata.tern.org.au/viewers/dawe-vocabs?uri=https://linked.data.gov.au/def/test/dawe-cv/d3f85cc2-f3e8-4900-a2ac-19fc27fd14f9
> 
> It's `growth form`.

Oh Alright! There was in this spreadsheet. So I wan wondering? It must have been dropped in latest updates.
https://docs.google.com/spreadsheets/d/1RZ6cXVjOZZhMKlhYyLNg73FucLKoL7LxRb8sp7jqMBM/edit#gid=0
