### ISSUE TITLE
`lut-fire-growth-forms` VS `lut-veg-growth-forms`

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#92]
These 2 APIs have similar categorical values.
http://vocabs.paratoo.tern.org.au:1337/api/lut-veg-growth-forms
http://vocabs.paratoo.tern.org.au:1337/api/lut-fire-growth-forms
Are they the same, if so, we prefer the tag `lut-veg-growth-forms` because it shows that `growth form` is for vegetation.

**Comment by j-robinson** [comment]
We have deleted `lut-fire-growth-forms` and will only use `lut-veg-growth-forms`
