### ISSUE TITLE
Are `growth form` and `plant growth form` the same?

### ISSUE THREAD

**Issue by junrongYu** [ternaustralia/dawe-rlp-vocabs#93]
They have similar definition and categorical values, if they are the same, then which label to use?

The determined API from #92 will be used.

**Comment by junrongYu** [comment]
This issue is related to #91 

By running the following query in https://graphdb.tern.org.au/sparql

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tern: <https://w3id.org/tern/ontologies/tern/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?moduleCollectionLabel ?parameterLabel ?parameterDefinition ?valueType ?featureType ?parameterMethod ?parameterSource ?categoricalCollectionLabel ?api
{
    ?moduleCollectionURI skos:member ?parameterURI ;
                         skos:prefLabel ?moduleCollectionLabel .
    ?parameterURI skos:prefLabel ?parameterLabel ;
    				tern:valueType ?valueTypeURI .
    ?valueTypeURI rdfs:label ?valueType .
    optional {?parameterURI skos:definition ?parameterDefinition .}
    optional {
            ?parameterURI tern:hasFeatureType ?featureTypeURI . 
            service <https://graphdb.tern.org.au/repositories/tern_vocabs_core> {
        ?featureTypeURI skos:prefLabel ?featureType .
    }}
    optional {
        ?parameterURI tern:hasMethod ?parameterMethodURI .
        ?parameterMethodURI skos:prefLabel ?parameterMethod .
    }
    optional {
        ?parameterURI dcterms:source ?parameterSource .
    }
    optional {
        ?parameterURI tern:hasCategoricalCollection ?categoricalCollectionURI .
        ?categoricalCollectionURI skos:prefLabel ?categoricalCollectionLabel ;
                                  dcterms:source ?api .
    }
    filter (?parameterLabel in ('growth form', 'plant growth form', 'flora growth form'))
}
order by ?parameterLabel
```

Their definition is the same but from different modules.
`growth form` and `plant growth form` have different categorical APIs but categorical values are the same.
`plant growth form` and `flora growth form` have different categorical values but similar labels.

**Comment by arunherb** [comment]
I think "growth form' , 'plant growth form' and 'flora growth form' all refer to the same parameter. I think it is better to keep one generic property called either 'flora growth form' or 'plant growth form' across all the modules and standardise its definition. I would keep 'plant growth form' for now, but we can confirm with the surveillance team and validate.

**Comment by junrongYu** [comment]
Cool thanks! Could you have a look at these 2 categorical APIs as well, they are both for growth forms, but I don't know the difference between them.
http://vocabs.paratoo.tern.org.au:1337/api/lut-targeted-survey-flora-growth-forms
http://vocabs.paratoo.tern.org.au:1337/api/lut-fire-growth-forms

**Comment by arunherb** [comment]
For some reason these two are overlapping- one has the growth form attributes from another module but with extended parameters. Check with the 'lut team' to see what they have to say.

**Comment by junrongYu** [comment]
Hi @arunherb , I am thinking whether `flora growth form` is the same as `growth form` and `plant growth form`. 

Categorical values for `growth form` and `plant growth form` are from this table:
<img width="205" alt="Screen Shot 2022-07-05 at 5 11 47 pm" src="https://user-images.githubusercontent.com/99153064/177270616-91eb614a-ee71-4a20-a2cd-fbc531dcba37.png">
Whereas `flora growth form` is from:
<img width="668" alt="Screen Shot 2022-07-05 at 5 12 55 pm" src="https://user-images.githubusercontent.com/99153064/177270798-2c6dfee1-59e8-4b36-b386-0a15366bf662.png">
Are they the same? Or it's better to give `flora growth form` a new label like `life form`?

**Comment by arunherb** [comment]
Hi Jun,
I see why the problem arises. So, as per the Targeted Survey protocol, they have 'life form' with a bunch of categorical variables. These variables look like they are just a variation of the NVIS categorical IDs, i.e. the 'growth form', with a few additions like 'herbs and forbs' and 'orchids'. I think 'life form' and 'growth form' has been loosely defined and used here, depending on the module. 
For now you can keep them as separate and discuss this issue with the surveillance and/or the lut team to give us more clarity. I would probably still club them into one parameter, say 'plant growth form' for example.

**Comment by j-robinson** [comment]
No they are not the same things, right now we are not using Appendix 7 data and we probably won't be. Unless there's a need for that table to be formalised as a categorical then we propose to delete `lut-targeted-survey-flora-growth-form`.

**Comment by junrongYu** [comment]
Hi @j-robinson , thanks for your reply!

> No they are not the same things

Do you mean `growth form`, `plant growth form` and `flora growth form` are different from each other? Or `growth form` and `plant growth form` are the same (they have the same categorical values), but they are different from `flora growth form` (in Targeted survey) ?
